# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-02 21:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=500, null=True)),
                ('group_description', models.TextField(max_length=500, null=True)),
                ('max_capacity', models.IntegerField(default=0)),
                ('members', models.CharField(max_length=100, null=True)),
                ('beneficiary_list', models.CharField(max_length=100, null=True)),
                ('Amount_to_be_saved', models.FloatField(default=0.0)),
                ('searchable', models.BooleanField(default=False)),
                ('group_admin', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100, null=True)),
                ('amount_saved', models.FloatField(default=0.0)),
                ('invite', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
