# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-22 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esusu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='amount_saved',
            field=models.FloatField(default=0.0),
        ),
    ]
